export const LABELS = {
  en: {
    appTitle: 'Village Need Analysis Tool',
    selectFolderLabel: 'Select Folder with Report',
    dropHint: 'Click here or drag & drop a folder containing .docx report + images',
    acceptedLabel: 'Accepts: .docx + image files (.jpg, .png)',
    analyzeLabel: 'Analyze Report',
    settingsLabel: 'Settings',
    villageDetailsLabel: 'Village Details',
    contextLabel: 'Context',
    findingsLabel: 'Key Findings',
    needsLabel: 'Needs Emerging',
    imagesLabel: 'Images',
    downloadExcelLabel: 'Download Excel',
    downloadWordLabel: 'Download Word Report',
    Village_Name: 'Village Name',
    District_State: 'District / State',
    Population: 'Population',
    Languages: 'Languages',
    Needs_Identified: 'Needs Identified',
    Documents: 'Documents',
    Need: 'Need',
    Category: 'Category',
    Priority: 'Priority',
    Source: 'Source',
    Suggested_Action: 'Suggested Action',
    Timeline: 'Timeline',
    Responsible_Party: 'Responsible Party',
    Budget_Estimate: 'Budget Estimate',
    Status: 'Status',
    Remarks: 'Remarks',
    High: 'High',
    Medium: 'Medium',
    Low: 'Low',
    All_Categories: 'All Categories',
    All_Priorities: 'All Priorities',
    Search_needs: 'Search needs...',
    Analyzing: 'Analyzing...',
    Processing: 'Processing...',
    Analyzing_report: 'Analyzing report with AI...',
    Extracting_text: 'Extracting text from DOCX...',
    Loading_images: 'Loading images...',
    No_DOCX_found: 'No DOCX file found in selected folder',
    No_images_found: 'No images found in selected folder',
    Analysis_complete: 'Analysis complete',
    API_error: 'API Error',
    Invalid_API_key: 'Invalid API key. Check your key and try again.',
    Network_error: 'Network error. Check your internet connection.',
    Primary_API_failed_HF_fallback: 'Primary API failed. Trying HuggingFace...',
    All_APIs_failed: 'All AI APIs failed. Please check your keys and try again.',
    downloadReport: 'Download Report',
    modalTitle: 'Download Report',
    modalDesc: 'Choose report language:',
    cancel: 'Cancel',
    fileCount: 'files selected',
    testSuccess: 'OK',
    testFailed: 'Failed',
    testing: 'Testing...',
    API_Key: 'API Key',
    useHFallback: 'Use HuggingFace if primary fails',
    villageName_ph: 'Village Name',
    districtState_ph: 'District / State',
    population_ph: 'Population',
    context_ph: 'Context summary...',
    Village_Context: 'Village Context',
    Village_Details: 'Village Details',
    village_name: 'village_name',
    district_state: 'district_state',
    population: 'population',
    context: 'context',
    needs: 'needs',
    key_findings: 'key_findings',
    languages_detected: 'languages_detected',
    category_water: 'Water & Sanitation',
    category_education: 'Education',
    category_healthcare: 'Healthcare',
    category_roads: 'Roads & Infrastructure',
    category_electricity: 'Electricity',
    category_agriculture: 'Agriculture',
    category_livelihood: 'Livelihood',
    category_environment: 'Environment',
    category_social: 'Social Welfare',
    category_other: 'Other',
    Summarize_Report: 'Summarize Report',
    Export_DOCX: 'Export DOCX',
    Export_Excel: 'Export Excel',
    Save_Edits: 'Save Edits',
    Revert: 'Revert',
    Summary_Data: 'Summary Data',
    Needs: 'Needs',
    Images: 'Images',
    Editor: 'Editor',
    OcrValidation: 'OCR Validation',
    Summarize: 'Summarize',
    clickToSummarize: 'Review the text on the left, then click Summarize to generate the village need analysis report.',
    savingEdits: 'Saving edits...',
    editsSaved: 'Edits saved',
    summarising: 'Summarising report...',
    exportDocx: 'Export DOCX',
    exportExcel: 'Export Excel',
    noNeedsFound: 'No needs found',
    matchNeeds: 'matching needs',
    allNeeds: 'all',
  },
  hi: {
    appTitle: 'गाँव ज़रूरत विश्लेषण उपकरण',
    selectFolderLabel: 'रिपोर्ट वाला फ़ोल्डर चुनें',
    dropHint: 'यहाँ क्लिक करें या .docx रिपोर्ट + चित्र वाला फ़ोल्डर खींचें और छोड़ें',
    acceptedLabel: 'स्वीकार करता है: .docx + चित्र फ़ाइलें (.jpg, .png)',
    analyzeLabel: 'रिपोर्ट विश्लेषण करें',
    settingsLabel: 'सेटिंग्स',
    villageDetailsLabel: 'गाँव विवरण',
    contextLabel: 'संदर्भ',
    findingsLabel: 'मुख्य निष्कर्ष',
    needsLabel: 'ज़रूरतें',
    imagesLabel: 'चित्र',
    downloadExcelLabel: 'Excel डाउनलोड',
    downloadWordLabel: 'Word रिपोर्ट डाउनलोड',
    Village_Name: 'गाँव का नाम',
    District_State: 'ज़िला / राज्य',
    Population: 'आबादी',
    Languages: 'भाषाएँ',
    Needs_Identified: 'पहचानी गई ज़रूरतें',
    Documents: 'दस्तावेज़',
    Need: 'ज़रूरत',
    Category: 'श्रेणी',
    Priority: 'प्राथमिकता',
    Source: 'स्रोत',
    Suggested_Action: 'सुझाई गई कार्रवाई',
    Timeline: 'समयसीमा',
    Responsible_Party: 'ज़िम्मेदार पक्ष',
    Budget_Estimate: 'बजट अनुमान',
    Status: 'स्थिति',
    Remarks: 'टिप्पणियाँ',
    High: 'उच्च',
    Medium: 'मध्यम',
    Low: 'निम्न',
    All_Categories: 'सभी श्रेणियाँ',
    All_Priorities: 'सभी प्राथमिकताएँ',
    Search_needs: 'ज़रूरतें खोजें...',
    Analyzing: 'विश्लेषण हो रहा है...',
    Processing: 'प्रोसेसिंग...',
    Analyzing_report: 'AI से रिपोर्ट विश्लेषण हो रही है...',
    Extracting_text: 'DOCX से टेक्स्ट निकाला जा रहा है...',
    Loading_images: 'चित्र लोड हो रहे हैं...',
    No_DOCX_found: 'चयनित फ़ोल्डर में कोई DOCX फ़ाइल नहीं मिली',
    No_images_found: 'चयनित फ़ोल्डर में कोई चित्र नहीं मिला',
    Analysis_complete: 'विश्लेषण पूर्ण',
    API_error: 'API त्रुटि',
    Invalid_API_key: 'अमान्य API कुंजी। अपनी कुंजी जाँचें और पुनः प्रयास करें।',
    Network_error: 'नेटवर्क त्रुटि। अपना इंटरनेट कनेक्शन जाँचें।',
    Primary_API_failed_HF_fallback: 'प्राथमिक API विफल। HuggingFace आज़मा रहे हैं...',
    All_APIs_failed: 'सभी AI API विफल। कृपया अपनी कुंजियाँ जाँचें।',
    downloadReport: 'रिपोर्ट डाउनलोड करें',
    modalTitle: 'रिपोर्ट डाउनलोड करें',
    modalDesc: 'रिपोर्ट की भाषा चुनें:',
    cancel: 'रद्द करें',
    fileCount: 'फ़ाइलें चुनी गईं',
    testSuccess: 'ठीक है',
    testFailed: 'विफल',
    testing: 'परीक्षण...',
    API_Key: 'API कुंजी',
    useHFallback: 'प्राथमिक विफल होने पर HuggingFace का उपयोग करें',
    villageName_ph: 'गाँव का नाम',
    districtState_ph: 'ज़िला / राज्य',
    population_ph: 'आबादी',
    context_ph: 'संदर्भ सारांश...',
    Village_Context: 'गाँव संदर्भ',
    Village_Details: 'गाँव विवरण',
    village_name: 'गाँव का नाम',
    district_state: 'ज़िला / राज्य',
    population: 'आबादी',
    context: 'संदर्भ',
    needs: 'ज़रूरतें',
    key_findings: 'मुख्य निष्कर्ष',
    languages_detected: 'पाई गई भाषाएँ',
    category_water: 'जल एवं स्वच्छता',
    category_education: 'शिक्षा',
    category_healthcare: 'स्वास्थ्य',
    category_roads: 'सड़क एवं अवसंरचना',
    category_electricity: 'बिजली',
    category_agriculture: 'कृषि',
    category_livelihood: 'आजीविका',
    category_environment: 'पर्यावरण',
    category_social: 'सामाजिक कल्याण',
    category_other: 'अन्य',
    Summarize_Report: 'रिपोर्ट सारांशित करें',
    Export_DOCX: 'DOCX निर्यात करें',
    Export_Excel: 'Excel निर्यात करें',
    Save_Edits: 'संपादन सहेजें',
    Revert: 'वापस लाएँ',
    Summary_Data: 'सारांश डेटा',
    Needs: 'ज़रूरतें',
    Images: 'चित्र',
    Editor: 'संपादक',
    OcrValidation: 'OCR सत्यापन',
    Summarize: 'सारांश',
    clickToSummarize: 'बाईं ओर के टेक्स्ट की समीक्षा करें, फिर गाँव ज़रूरत विश्लेषण रिपोर्ट बनाने के लिए सारांशित करें पर क्लिक करें।',
    savingEdits: 'संपादन सहेजा जा रहा है...',
    editsSaved: 'संपादन सहेजे गए',
    summarising: 'रिपोर्ट सारांशित की जा रही है...',
    exportDocx: 'DOCX निर्यात करें',
    exportExcel: 'Excel निर्यात करें',
    noNeedsFound: 'कोई ज़रूरत नहीं मिली',
    matchNeeds: 'मिलती ज़रूरतें',
    allNeeds: 'सभी',
  },
};

let currentLang = 'en';
export function setLang(lang) { currentLang = lang; }
export function getLang() { return currentLang; }
export function t(key) { return LABELS[currentLang][key] || key; }
export function useLabels() {
  return { t, currentLang, setLang: (l) => { currentLang = l; } };
}